name: Deploy

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker build --tag docker.pkg.github.com/chickaree/parser/parser:${GITHUB_REF} --tag docker.pkg.github.com/chickaree/parser/parser:latest --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} .
    - run: docker login https://docker.pkg.github.com -u chickaree --password ${{ secrets.GITHUB_TOKEN }}
    - run: docker push docker.pkg.github.com/chickaree/parser/parser:latest

